'use strict';
/**
 * Policy availability and assessment-maximum validation.
 *
 * Which transmutation policies the UI may offer, and at what confidence.
 * All three policies are usable. They differ in how strongly their lookup data
 * has been proven, which the UI surfaces rather than hides.
 *
 * Current state of the shipped tables (see `_verification` in the JSON):
 *   70%  GRADE_VERIFIED — extracted from the instructor's live workbook and
 *                         proven to reproduce all 167 real student grades with
 *                         zero mismatches. This is the standing release gate.
 *   50%  STRUCTURAL     — transcribed from the source PDF; every column starts
 *   60%  STRUCTURAL       at 50, reaches 100 at its maximum, and rises
 *                         monotonically. Not grade-verified, because the real
 *                         dataset uses only the 70% policy.
 *
 * "Structurally verified" is a real bar, not a shrug: the checks that caught the
 * original mis-transcription (a perfect score not reaching 100, a non-monotonic
 * dip) run over every column in the test suite.
 */

const CONFIDENCE = {
  /** Proven against real student grades. */
  GRADE_VERIFIED: 'grade-verified',
  /** Transcribed from the source and structurally sound; no real-grade fixture. */
  STRUCTURAL: 'structurally-verified',
};

const STRUCTURAL_NOTE =
  'Copied from the university tables and checked over: every column climbs steadily from ' +
  '50 to 100. It has not been tried against a finished grade sheet yet, because the one ' +
  'we checked against used the 70% table throughout.';

/**
 * Columns that were DERIVED rather than transcribed, as policy -> [maxPoints].
 *
 * Every other column in the shipped data was copied from the university tables.
 * These were not available from either source and are reconstructed, so they are
 * tracked here and the UI says so wherever one is chosen. This is deliberately a
 * short list: a derived column is a stopgap until the real one can be read off
 * the university table, not a licence to invent more.
 *
 * 70% / 20 points
 *   The instructor's workbook has only seven columns (5, 10, 15, 25, 30, 35, 40)
 *   and no 20-point column to copy, while the 50% and 60% tables both have one —
 *   so its absence was a gap in what could be transcribed, not a rule that a
 *   20-point assessment is disallowed. Instructors do set 20-point work, so the
 *   column is generated by the rule the real columns already follow: 50 at a raw
 *   zero, 70 at the policy's passing mark, 100 at the maximum, straight lines
 *   between, rounded to whole numbers. That rule reproduces the real 70% 10, 15,
 *   25 and 50-point columns exactly, and — the direct check that matters here —
 *   the real 50% and 60% 20-point columns exactly. It also stays at or below the
 *   60% column at every raw score, as every genuine 70% column does.
 */
const DERIVED_MAXIMUMS = {
  70: [20],
};

/** Was this column reconstructed rather than copied from the university table? */
function isDerivedMaximum(maxPoints, policy) {
  const list = DERIVED_MAXIMUMS[String(policy)] || DERIVED_MAXIMUMS[Number(policy)] || [];
  return list.includes(Number(maxPoints));
}

/**
 * What to tell an instructor who has picked a derived column. Returned as a
 * warning rather than an error: the value is usable and structurally sound, but
 * they are the one who can check it against the printed table.
 */
function derivedMaximumNote(maxPoints, policy) {
  return (
    `The ${policy}% table we were given has no ${maxPoints}-point column, so this one is ` +
    `worked out from the columns either side of it. It follows the same pattern as the ` +
    `rest of the table and matches the ${maxPoints}-point columns in the 50% and 60% ` +
    `tables exactly. Scores out of ${maxPoints} will grade sensibly, but check one ` +
    `result against your printed table before you submit.`
  );
}

/**
 * Per-policy status. `selectable` drives whether the UI offers it at all.
 */
const POLICY_STATUS = {
  70: {
    policy: '70',
    label: '70%',
    confidence: CONFIDENCE.GRADE_VERIFIED,
    selectable: true,
    isDefault: true,
    // User-facing wording stays general: the person reading it is the
    // instructor, so "the instructor's workbook" reads as someone else's.
    note: 'Checked against 167 real student grades across 6 sections. Every one matched.',
  },
  60: {
    policy: '60',
    label: '60%',
    confidence: CONFIDENCE.STRUCTURAL,
    selectable: true,
    isDefault: false,
    note: STRUCTURAL_NOTE,
  },
  50: {
    policy: '50',
    label: '50%',
    confidence: CONFIDENCE.STRUCTURAL,
    selectable: true,
    isDefault: false,
    note: STRUCTURAL_NOTE,
  },
};

/** Policy offered when a course does not specify one. */
const DEFAULT_POLICY = '70';

/** Every policy present in the data, with its status. */
function allPolicies(tables) {
  return tables.policies().map((p) => ({
    ...(POLICY_STATUS[p] || {
      // An unknown policy appearing in the data has no provenance, so it is
      // listed but never offered until someone vouches for it here.
      policy: String(p),
      label: `${p}%`,
      confidence: null,
      selectable: false,
      isDefault: false,
      note: 'Unrecognised policy; not offered.',
    }),
    supportedMaximums: tables.supportedMaximums(p),
  }));
}

/** Only the policies the UI may offer. */
function selectablePolicies(tables) {
  return allPolicies(tables).filter((p) => p.selectable);
}

/** Status for one policy. */
function policyStatus(policy) {
  return POLICY_STATUS[String(policy)] || null;
}

/** True when a course may use this policy. */
function isSelectable(policy) {
  const s = policyStatus(policy);
  return !!(s && s.selectable);
}

/**
 * Validate an assessment's point maximum against the active policy.
 *
 * Returns a result rather than throwing: the spec wants the app to warn on an
 * obvious mismatch while still letting an instructor proceed deliberately.
 *
 * @returns {{ok:boolean, level:'ok'|'error', message:string|null, supported:number[]}}
 */
function validateMaxPoints(maxPoints, policy, tables) {
  const supported = tables.supportedMaximums(policy);
  const n = Number(maxPoints);
  if (!Number.isFinite(n) || n <= 0) {
    return {
      ok: false,
      level: 'error',
      message: 'The point value has to be a number above zero.',
      supported,
    };
  }
  if (!tables.supports(policy, n)) {
    return {
      ok: false,
      level: 'error',
      message:
        `The ${policy}% table has no column for ${n} points, so a score out of ${n} ` +
        `cannot be looked up. You can use: ${supported.join(', ')}.`,
      supported,
    };
  }
  // Usable, but reconstructed rather than copied from the university table, so
  // the instructor is told and asked to spot-check one result.
  if (isDerivedMaximum(n, policy)) {
    return {
      ok: true,
      level: 'warning',
      derived: true,
      message: derivedMaximumNote(n, policy),
      supported,
    };
  }
  return { ok: true, level: 'ok', derived: false, message: null, supported };
}

/**
 * Which of a course's assessments would be stranded by a policy change.
 * Used to warn before switching. All three policies now cover 5-50 in fives, so
 * this only catches a deliberate override like a 17- or 100-point assessment.
 *
 * @param {Array<{id?:*, name:string, maxPoints:number}>} assessments
 * @returns {Array<{name:string, maxPoints:number}>} the stranded ones
 */
function strandedByPolicy(assessments, newPolicy, tables) {
  return (assessments || [])
    .filter((a) => !tables.supports(newPolicy, a.maxPoints))
    .map((a) => ({ name: a.name, maxPoints: a.maxPoints }));
}

module.exports = {
  CONFIDENCE,
  DEFAULT_POLICY,
  POLICY_STATUS,
  DERIVED_MAXIMUMS,
  isDerivedMaximum,
  derivedMaximumNote,
  allPolicies,
  selectablePolicies,
  policyStatus,
  isSelectable,
  validateMaxPoints,
  strandedByPolicy,
};
